### ISSUE TITLE
Review: TransportDataEntry.jsx

### ISSUE THREAD

**Issue by edwin-zheng** [virtual-manoa-coders/vmc-uILA#18]
## Overview

This review is to check the current state of TransportDataEntry.jsx.

## Review Branch

review-018

## Files to review

* [TransportDataEntry.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/master/app/imports/ui/pages/TransportDataEntry.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

February 9th, 12pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by edwin-zheng** [comment]
JS-08 
- Line 30, Comment seems unecessary for JSDoc inclusion

ESLINT-01
- Line 8, ESLint error about putting a space before the '}' in imports

METEOR-02
- mdg:validated-method package not present from my search.

**Comment by angcylau** [comment]
Arch-01: Directories use lowercase with - between words.
The 'userTransportation' directory should be named 'user-transportation'

L8: ESLINT-01: Object-curly spacing. A space is required before '}'

**Comment by s-rathyen** [comment]
DESIGN-04:
- Move comment block ToDo to an issue

**Comment by christianjensenv** [comment]
Line 8 - space before curly bracket(easy)
Line 54 - Change header from Add stuff to something more meaningful
Line 59- Miles in numfield shouldn't go negative

**Comment by bradenbetz** [comment]
JS-01
Line 50 - Possibly rename this variable fRef, a bit ambiguous 

JS-08
Line 30 - Probably don't need this comment, pretty basic

**Comment by JiajunK** [comment]
Line 40 a specific error would be helpful instead of just 'error'

**Comment by tgabatin** [comment]
ES-Lint:
Line 08: Space needed before bracket

JS-08:
Line 30: Comment not necessary. 
Line 40: Error message needs to be specific to the error. 
Line 54: "Add Stuff" is not relevant
