### ISSUE TITLE
Review: UserProfile.jsx

### ISSUE THREAD

**Issue by JiajunK** [virtual-manoa-coders/vmc-uILA#44]
## Overview

We will be reviewing the user profile page and any associated database collection files. 

## Review Branch

[review-044](https://github.com/virtual-manoa-coders/vmc-uILA/tree/review-044)

## Files to review

* [UserProfile.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-044/app/imports/ui/pages/UserProfile.jsx)
* [UserInfo.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-044/app/imports/api/userData/UserInfo.js)
* [UserTransportation](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-044/app/imports/api/userData/UserTransportation.js)
* [UserVehicles.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-044/app/imports/api/userVehicles/UserVehicles.js)

## Checklists
* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

03/09/2021 12:00pm

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by edwin-zheng** [comment]
UserProfile.jsx
Design-05: Line 29
JS-08: Line 41
React-09 (unless state is planned to be added later)

UserInfo.js
Design-05: Line 8, 10
Meteor-03
Meteor-04

UserTransporation.js
Design-05: Line 8, 10
Meteor-03
Meteor-04

UserVehicles.js
Design-05: Line 7, 9, 76
Meteor-03
Meteor-04

**Comment by s-rathyen** [comment]
UserInfo.js
DESIGN-05
	L8 - unnecessary comment? (Self-explanatory)

Userprofile.js 
DESIGN-07
	L34 - specify error message
DESIGN-07
	L125, 126, 127 - subscription variable names are vague

**Comment by JiajunK** [comment]
UserProfile.jsx:
Design-05: Line 29, can be more descriptive of where the data is being inserted or what the submit does. Submit(data) is pretty self-explanatory so the comment could expand on it more. 
Line 34: error message should be more specific

UserTransportation.js:
Design-05: Line 5: transportation usage may be hard to understand, better naming may be "transportation method"

UserVehicles.js:
Deisgn-05: Line 75: //Price of car and carPrice: Number is self-explanatory enough

**Comment by angcylau** [comment]
UserProfile.jsx
Arch-01: Directories 'userData' and 'userVehicles' should be 'user-data' and 'user-vehicles'.
METEOR-03: Wrap collections in a class with define, update, and removeIt methods.
L15, 26, 29, 41, 46, 114: JS-08: Comments that start with '/**' are reserved for and processed by JSDoc.
L51: REACT-07: Don't retrieve collection data inside renderPage()

**Comment by bradenbetz** [comment]
ESLINT-01 - UserVehicles.js line 3, unused import

DESIGN-05 - UserVhicles.js lines 74 & 76, redundant comments

METEOR-01 - Insecure package

**Comment by patimapoochai** [comment]
Arch-03: Move userVehicles into /api/userData
Design-05: Remove comments from each collection
METEOR-03: Wrap the collections in a class
METEOR-04: Create methods with validations
TEST-UNIT-01: No unit tests, might want to implement it in a later milestone


UserProfile.jsx:
REACT-09: Transform class into a function
TEST-ACCEPTANCE-01: Lacking isDisplayed(), might want to implment it in a later milestone

**Comment by cammoore** [comment]
Lots of code for a single review.

UserProfile.jsx

JS-08 comments

REACT-09 L27 prefer functions.

REACT-06: L51 use withTracker for collection access.
L49, L53 could be consts passed in via withTracker

UserInfo.js

UserTransportation.js

JS L16 Might want to export this array so we can use it in other
places like the UI.

UserVehicles.js

JS-08 comments

JS L19-66 might want to export this array so we can use it in other
places. Similar comment on L72
