### ISSUE TITLE
Add function for travel patterns

### ISSUE THREAD

**Issue by angcylau** [virtual-manoa-coders/vmc-uILA#55]
Please do work for this task in a branch called issue-55.

Allow users to create common trips to simplify trip logging.

Users should be able to 
- name their commute (work, school, gym, etc.,)
- enter total distance
- save/edit/delete

**Comment by JiajunK** [comment]
The form has semi-working checkbox and input form, a new .js file to store the data has been created. Not too sure why it still doesn't work, but this issue still needs to be worked on.
