### ISSUE TITLE
Review: CO2Graph.jsx and CO2GraphWithTimeRange.jsx

### ISSUE THREAD

**Issue by patimapoochai** [virtual-manoa-coders/vmc-uILA#62]
## Overview

- The two files are graph widgets, one is a basic component and another implements reactive time change
- Check the usage of State Hooks and Functional Components
- Does the aesthetic, layout, and placement of the component fit the target user?

## Review Branch

[review-061](../tree/review-061)

## Files to review

* [CO2Graph.jsx](../tree/review-061/app/imports/ui/components/Visualization/CO2Graph.jsx)
* [CO2GraphWithTimeRange.jsx](../tree/review-061/app/imports/ui/components/Visualization/CO2GraphWithTimeRange.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [Meteor](../tree/master/checklists/meteor-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)
* [Testing](../tree/master/checklists/testing-checklist.md)

## Due date

March 30, 2021

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by angcylau** [comment]
CO2Graph.jsx

- L34/54: ESLINT-01: variable 'dataObject' is redundant; no need to create a variable, just return the stuff in 'dataObject' instead.

CO2GraphWithTimeRange.jsx

- L2, L5: ESLINT-01: 'Divider' and 'TextHeader' is defined but never used.

**Comment by patimapoochai** [comment]
CO2Graph.jsx:
Design-05: L17-19, L69-70: Maybe convert to JS Doc?

CO2GraphWithTimeRange.jsx:
ESLINT-01: L2,5

REACT-04: Destructure props on the default exports
TEST-ACCEPTANCE-01

**Comment by tgabatin** [comment]
CO2Graph.jsx:
Line 34: ESLINT-01 'dataObject' unused

CO2GraphWithTimeRange.jsx:
Line 2: ESLINT-01 Unused import 'Divider'
Line 5: ESLint-01 Unused import 'TextHeader'

**Comment by bradenbetz** [comment]
C02Graph.jsx

Design-04: Lines 17-19 & 69-70 can be put into JSDoc

C02GraphWithTimeRange.jsx

ESLINT-01: Lines 2 & 5 Divider and TextHeader are unused

Design-07: Could use a quick comment or JSDoc to familiarize anyone without the knowledge of chart.js on how setting up a chart works

METEOR-01 Insecure package still exists

**Comment by JiajunK** [comment]
CO2Graph.jsx:
Design 08 - Line 41/42: could condense this in the css file instead of putting inline style
CO2GraphWithTimeRange.jsx:
Design 03 - Line 22: when would it reach default? Maybe leaving a comment would be beneficial

**Comment by cammoore** [comment]
CO2Graph.jsx

L39, 46 Should these strings be const exported from CO2CalculationTimespan
L71 deconstruct object.

CO2GraphWithTimeRange.jsx

L7 deconstruct object
L8, 13, 16, 19 Should be defined object Keys exported from somewhere.
