### ISSUE TITLE
Review: Dashboard

### ISSUE THREAD

**Issue by edwin-zheng** [virtual-manoa-coders/vmc-uILA#95]
## Overview

The goal of this review is to look over the Dashboard and to make sure it conforms to our standards.

## Review Branch

[review-95](https://github.com/virtual-manoa-coders/vmc-uILA/tree/review-095)

## Files to review

* [Dashboard.jsx](https://github.com/virtual-manoa-coders/vmc-uILA/blob/review-095/app/imports/ui/pages/Dashboard.jsx)

## Checklists

* [Architecture](../tree/master/checklists/architecture-checklist.md)
* [Design](../tree/master/checklists/design-checklist.md)
* [JS](../tree/master/checklists/js-checklist.md)
* [React](../tree/master/checklists/react-checklist.md)

## Due date

4/27/2021

## For more information

The review process is documented at: http://courses.ics.hawaii.edu/ics414s21/morea/review/reading-idpm-review.html

**Comment by edwin-zheng** [comment]
Dashboard.jsx

JS-08
 - L18: comment doesn't need to be JSDoc comment probably
 - L136: Referencing Stuff instead of Dashboard props, change to // or /* */ type comments
 - L145: Use // or /* */

ESLint-01
 - L3: ESLint supress unecessary, just delete unused imports from semantic-ui in line 4

REACT-09: Could convert component, since no state exists.

**Comment by angcylau** [comment]
Arch-01: Directories should use lowercase with '-' between words. 'userData' should be 'user-data', 'userVehicles' should be 'user-vehicles'.

ESLINT-01: L4: Unused 'Container' and 'Table' imports.

ESLINT-01: L60: XML tag has empty body.

**Comment by bradenbetz** [comment]
JS-08: Probably do not need this JSDoc L18

ESLint-01: Unused imports L4

DESIGN-05: Could remove this comment on L147

**Comment by cammoore** [comment]
L57 - 62 What is this for?
https://github.com/virtual-manoa-coders/vmc-uILA/blob/a1512b46a731c15a452432c7ce606c00cca12496/app/imports/ui/pages/Dashboard.jsx#L57-L62

L74, 84, 94, 104 Why hidden Divider?

L136 Bad comment

REACT-06 Define constants in withTracker https://github.com/virtual-manoa-coders/vmc-uILA/blob/a1512b46a731c15a452432c7ce606c00cca12496/app/imports/ui/pages/Dashboard.jsx#L151-L156

**Comment by tgabatin** [comment]
ESLINT-01: Unused imports

ARCH-01: Naming convention directory change

**Comment by patimapoochai** [comment]
Design-01: L27 - L52: Put these into a component?
Design-05: L18: Comments from template; doesn't add any new information to render()

React-09: This component is still a class. Should refractor into a function

**Comment by JiajunK** [comment]
Line 3: remove the esLint suppressant before final product
Line 136: irrelevant comment of "stuff", replace with more relevant information
Line148~150: better constant names might be helpful
